name: ML_model CI

on:
  push:
    paths:
      - 'ml_model/**'
      - '.github/workflows/ml_model-check.yml'
  pull_request:
    paths:
      - 'ml_model/**'
      - '.github/workflows/ml_model-check.yml'

jobs:
  ml_model-check:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ§¾ Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: ğŸ“¦ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest catboost pandas

      - name: ğŸ” Lint with flake8
        run: |
          echo "Running flake8..."
          flake8 ml_model

      - name: âœ… Run ml_model tests
        run: |
          echo "Running tests..."
          pytest test/test_recomendation.py
